version: "3.2"

services:
  traefik:
    image: traefik:1.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/acme.json:/etc/traefik/acme/acme.json
      - ./configs/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - webgateway
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  webgateway:
    external: true
  traefik:
    driver: overlay
